name: net_base
description: A new Flutter project.
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # 网络请求
  dio: ^5.0.0
  format_dio_logger:
    git:
      url: https://github.com/thintime-X/format_dio_logger.git
#      ref: '0869222'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
